/**
 * Copilot custom agent generation (SPEC §7 Level 1).
 *
 * Generates the five `.github/agents/*.agent.md` workspace files from the
 * current Agent Room virtual team. Generated files carry a content-hash
 * marker so later syncs can tell "still exactly what we generated" apart
 * from "the user edited this" — a user-edited file is never overwritten
 * without explicit confirmation, and a file without our marker is treated
 * as user-owned.
 *
 * This module deliberately has no dependency on the `vscode` module so the
 * §18 generation and no-overwrite tests can run against it directly.
 */

import { createHash } from "crypto";
import * as fs from "fs/promises";
import * as path from "path";
import { RoleDefinition, VirtualAgent } from "./Types";

/** Fixed file set from SPEC §7 Level 1. */
export const CUSTOM_AGENT_FILE_SPECS = [
  { agentId: "atlas", fileName: "atlas-planner.agent.md" },
  { agentId: "forge", fileName: "forge-coder.agent.md" },
  { agentId: "sentinel", fileName: "sentinel-reviewer.agent.md" },
  { agentId: "gauge", fileName: "gauge-tester.agent.md" },
  { agentId: "scout", fileName: "scout-researcher.agent.md" }
] as const;

const MARKER_PREFIX = "<!-- agent-room:generated content-hash=";
const MARKER_SUFFIX =
  " — generated by Agent Room. Edit freely; Agent Room never overwrites a modified file without your confirmation. -->";
const MARKER_PATTERN = /^<!-- agent-room:generated content-hash=([0-9a-f]{64}) /;

const HANDOFF_GUIDANCE: Record<string, string> = {
  atlas:
    "Hand your plan to Forge (Coder) for implementation. Flag security-sensitive areas " +
    "for Sentinel (Reviewer / Security Auditor) and call out behavior that Gauge (Tester) " +
    "should cover. Do not implement the plan yourself.",
  forge:
    "After implementing, hand off to Sentinel (Reviewer / Security Auditor) for review and " +
    "to Gauge (Tester) for coverage. If requirements are unclear, send the question back to " +
    "Atlas (Planner) instead of guessing.",
  sentinel:
    "Report findings back to Forge (Coder) for fixes, ordered by severity. Escalate scope " +
    "or requirement questions to Atlas (Planner). Approval authority stays with the human.",
  gauge:
    "Report missing coverage and failing cases to Forge (Coder). Confirm with Sentinel " +
    "(Reviewer) which risky areas deserve tests first.",
  scout:
    "Deliver cited findings to Atlas (Planner) for planning or to whoever asked. Never " +
    "make implementation decisions; your job ends at verified, sourced information."
};

const EXPECTED_OUTPUT: Record<string, string> = {
  atlas: "A numbered plan with assumptions, dependencies, risks, and open questions.",
  forge:
    "An implementation summary listing the exact files changed. If no files were changed, say so honestly.",
  sentinel: "Findings grouped by severity, each tied to a specific location, with concrete remediation steps.",
  gauge: "A list of missing test cases (names, inputs, expected outcomes) and the verification results.",
  scout: "Findings with a source link for every claim, and an explicit verdict where one was requested."
};

export interface CopilotCustomAgentGeneratorOptions {
  workspaceRoot: string;
  /** Relative to workspaceRoot (default `.github/agents`), or absolute. */
  customAgentsDirectory: string;
  virtualAgents: VirtualAgent[];
  roles: RoleDefinition[];
}

export type CustomAgentFileAction = "create" | "update" | "skipUnchanged" | "skipModified";

export interface GeneratedCustomAgentFile {
  agentId: string;
  fileName: string;
  absolutePath: string;
  /** Full file content including the generation marker line. */
  content: string;
}

export interface CustomAgentSyncEntry {
  file: GeneratedCustomAgentFile;
  action: CustomAgentFileAction;
}

export interface CustomAgentSyncPlan {
  directory: string;
  entries: CustomAgentSyncEntry[];
  /** Agent ids from the §7 file set that are missing from the current team. */
  missingAgents: string[];
}

export interface CustomAgentSyncResult {
  written: string[];
  unchanged: string[];
  skippedModified: string[];
  overwrittenModified: string[];
}

function sha256(text: string): string {
  return createHash("sha256").update(text, "utf8").digest("hex");
}

function markerLine(body: string): string {
  return `${MARKER_PREFIX}${sha256(body)}${MARKER_SUFFIX}`;
}

export class CopilotCustomAgentGenerator {
  constructor(private readonly options: CopilotCustomAgentGeneratorOptions) {}

  directory(): string {
    return path.isAbsolute(this.options.customAgentsDirectory)
      ? this.options.customAgentsDirectory
      : path.join(this.options.workspaceRoot, this.options.customAgentsDirectory);
  }

  /** Pure generation: the five §7 files for the current team. */
  generateFiles(): { files: GeneratedCustomAgentFile[]; missingAgents: string[] } {
    const files: GeneratedCustomAgentFile[] = [];
    const missingAgents: string[] = [];
    for (const spec of CUSTOM_AGENT_FILE_SPECS) {
      const agent = this.options.virtualAgents.find((entry) => entry.id === spec.agentId);
      if (!agent) {
        missingAgents.push(spec.agentId);
        continue;
      }
      const body = this.fileBody(agent);
      files.push({
        agentId: spec.agentId,
        fileName: spec.fileName,
        absolutePath: path.join(this.directory(), spec.fileName),
        content: `${markerLine(body)}\n${body}`
      });
    }
    return { files, missingAgents };
  }

  /** Compare generated content against what is on disk. */
  async plan(): Promise<CustomAgentSyncPlan> {
    const { files, missingAgents } = this.generateFiles();
    const entries: CustomAgentSyncEntry[] = [];
    for (const file of files) {
      entries.push({ file, action: await this.classify(file) });
    }
    return { directory: this.directory(), entries, missingAgents };
  }

  /**
   * Write the plan. `skipModified` entries are only written when
   * `overwriteModified` is true — i.e. after the user explicitly confirmed.
   */
  async apply(
    plan: CustomAgentSyncPlan,
    options: { overwriteModified: boolean } = { overwriteModified: false }
  ): Promise<CustomAgentSyncResult> {
    const result: CustomAgentSyncResult = {
      written: [],
      unchanged: [],
      skippedModified: [],
      overwrittenModified: []
    };
    await fs.mkdir(plan.directory, { recursive: true });
    for (const entry of plan.entries) {
      switch (entry.action) {
        case "skipUnchanged":
          result.unchanged.push(entry.file.fileName);
          break;
        case "create":
        case "update":
          await fs.writeFile(entry.file.absolutePath, entry.file.content, "utf8");
          result.written.push(entry.file.fileName);
          break;
        case "skipModified":
          if (options.overwriteModified) {
            await fs.writeFile(entry.file.absolutePath, entry.file.content, "utf8");
            result.overwrittenModified.push(entry.file.fileName);
          } else {
            result.skippedModified.push(entry.file.fileName);
          }
          break;
      }
    }
    return result;
  }

  private async classify(file: GeneratedCustomAgentFile): Promise<CustomAgentFileAction> {
    let existing: string;
    try {
      existing = await fs.readFile(file.absolutePath, "utf8");
    } catch (error) {
      if (isMissingFileError(error)) return "create";
      throw error;
    }
    const newlineIndex = existing.indexOf("\n");
    const firstLine = newlineIndex === -1 ? existing : existing.slice(0, newlineIndex);
    const match = MARKER_PATTERN.exec(firstLine.trim());
    // No Agent Room marker: the user owns this file.
    if (!match) return "skipModified";
    const existingBody = newlineIndex === -1 ? "" : existing.slice(newlineIndex + 1);
    // Marker hash no longer matches the body: the user edited it.
    if (sha256(existingBody) !== match[1]) return "skipModified";
    const newBody = file.content.slice(file.content.indexOf("\n") + 1);
    return existingBody === newBody ? "skipUnchanged" : "update";
  }

  /** Markdown body with every section SPEC §7 Level 1 requires. */
  private fileBody(agent: VirtualAgent): string {
    const roles = this.options.roles.filter((role) => agent.assignedRoleIds.includes(role.id));
    const roleNames = roles.map((role) => role.name).join(", ") || "no roles assigned";
    const roleSections = roles
      .map((role) => `### ${role.name}\n\n${role.instructions}`)
      .join("\n\n");
    const lines = [
      `# ${agent.displayName}`,
      "",
      "## Description",
      "",
      agent.description,
      "",
      "## Relationship to the Agent Room Virtual Team",
      "",
      `This custom agent represents the Agent Room virtual team member **${agent.displayName}** ` +
        `(${roleNames}). It was generated by the Agent Room VS Code extension; regenerate it ` +
        `with "Agent Room: Generate Copilot Custom Agents" after changing the team.`,
      "",
      "## Role Instructions",
      "",
      roleSections || "_No role instructions: this team member currently has no assigned roles._",
      "",
      "## Expected Behavior",
      "",
      `Act only within the roles listed above (${roleNames}). Stay within the task you were ` +
        "given, state your assumptions, and ask instead of guessing when requirements are " +
        "unclear. Be honest about what you can and cannot see in the workspace.",
      "",
      "## Safety Rules",
      "",
      "- Do not run destructive actions unless explicitly requested and allowed.",
      "- Never expose secrets, API keys, or environment variables in any output.",
      "- Never claim a file was changed unless it actually changed; list exact files when you change them.",
      "- Do not pretend to communicate with other agents outside the visible conversation.",
      "- The human user is the Final Approver; never claim final approval yourself.",
      "",
      "## Handoff Guidance",
      "",
      HANDOFF_GUIDANCE[agent.id] ??
        "Hand results back to the requester and name which team member should act next.",
      "",
      "## Expected Output Format",
      "",
      EXPECTED_OUTPUT[agent.id] ?? "A concise result the next team member can act on directly.",
      ""
    ];
    return lines.join("\n");
  }
}

function isMissingFileError(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    "code" in error &&
    (error as { code?: unknown }).code === "ENOENT"
  );
}
